---

- name: Install dependencies
  apt:
    name: zip
    state: present
  tags:
    - packages

- name: Get gophish from release with sha256 check
  get_url:
    url: "https://github.com/gophish/gophish/releases/download/{{ gophish_version }}/gophish-{{ gophish_version }}-linux-64bit.zip"
    dest: "/opt/gophish-{{ gophish_version }}-linux-64bit.zip"
    checksum: sha256:{{ gophish_version_hash }}
  tags:
    - gophish

- name: Ensure Gophish dir exists
  file:
    path: /opt/gophish
    state: directory
    mode: '0755'
  tags:
    - gophish

- name: Unzip gophish archive
  unarchive:
    src: "/opt/gophish-{{ gophish_version }}-linux-64bit.zip"
    dest: /opt/gophish
    remote_src: true
  tags:
    - gophish

- name: Ensure exec permissions on gophish binary
  file:
    path: /opt/gophish/gophish
    mode: '755'
  tags:
    - gophish

- name: Copy gophish.sh status script
  template:
    src: opt_gophish_gophish.sh
    dest: /opt/gophish/gophish.sh
    owner: root
    group: root
    mode: '0755'
    remote_src: no
  tags:
    - gophish

- name: Copy service file
  copy:
    src: lib_systemd_system_gophish.service
    dest: /lib/systemd/system/gophish.service
    owner: root
    group: root
    mode: '0755'
    remote_src: no
  tags:
    - gophish

- name: Ensure gophish service is running
  systemd:
    name: gophish
    daemon_reload: true
    state: started
  tags:
    - gophish

#- name: Display admin OTP login creds
#  shell: /bin/grep -o "Please login with the username admin and the password .*" /var/log/gophish.err | sed 's/"//g'
#  register: adminpw

# - debug: msg="{{ adminpw.stdout_lines | quote }}"
